version: 2.1 # use CircleCI 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      # - run: |
      #     echo "Checking Docker username: $DOCKER_LOGIN"
      #     echo "Checking Docker password: $DOCKER_PASSWORD"
      - docker/check:
          docker-username: DOCKER_LOGIN  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: DOCKER_PASSWORD  # DOCKER_PASSWORD is the default value
      - docker/build:
          image: $DOCKER_REPO/assig4.5my_app
      - docker/push:
          image: $DOCKER_REPO/assig4.5my_app
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker      
  #     - heroku/install
  #     - checkout
  #     - run:
  #         name: Heroku Container Push
  #         command: | 
  #             heroku container:login
  #             heroku stack:set container -a shennan-su-devops
  #             heroku container:push web -a shennan-su-devops
  #             heroku container:release web -a shennan-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - publish